### ISSUE TITLE
Create a README file

### ISSUE THREAD

**Issue by hdiogenes** [kytos/end-to-end-tests#1]
Minimal needs are instructions on how to:
- Install prerequisites
- (Successfully) run the test suite

**Comment by hdiogenes** [comment]
```
git clone git@github.com:kytos/end-to-end-tests.git
cd end-to-end-tests

apt install docker-compose openvswitch-switch
sudo dockerd
sudo docker-compose up
```

**Comment by hdiogenes** [comment]
I've talked to @italovalcy and he told me you already had that @dgarc330, so I've assigned this issue to you, OK?

**Comment by dgarc330** [comment]
README file was created on September 21st.
